### ISSUE TITLE
Error running a published app

### ISSUE THREAD

**Issue by Glusk** [ExtCore/ExtCore-Sample-Mvc#3]
My issue may be related to #2.

I've downloaded and built this (bfbe96b6) version of the project.
I've copied `ExtCore-Sample-Mvc\src\Extension\bin\Debug\netstandard2.0\Extension.dll` to `ExtCore-Sample-Mvc\src\WebApplication\Extensions\` and successfully ran the server both in:
- Visual Studio debug mode (IIS)
- stand-alone mode

  ```
  cd ExtCore-Sample-Mvc\src\WebApplication\bin\Debug\netcoreapp2.2
  dotnet WebApplication.dll
  ```

---

Now I'd like to run a *published* build, using [*these publish settings*](https://imgur.com/a/hVl7FCP).

After running:
  ```
  cd ExtCore-Sample-Mvc\src\WebApplication\bin\Debug\netcoreapp2.2\publish
  dotnet WebApplication.dll
  ```
I get this warning:
```
warn: ExtCore.WebApplication[0]
      Discovering and loading assemblies from path '<path_to_my_project_parent_folder>\ExtCore-Sample-Mvc\src\WebApplication\bin\Debug\netcoreapp2.2\publish/Extensions' skipped: path not found            
  ```
After copying `ExtCore-Sample-Mvc\src\WebApplication\Extensions\Extension.dll` to `ExtCore-Sample-Mvc\src\WebApplication\bin\Debug\netcoreapp2.2\publish\Extensions\` the server fires up without warnings.

But I get this error after a `GET` request to the server:
```
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:5000/
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
      Route matched with {action = "Index", controller = "Default"}. Executing action Extension.Controllers.DefaultController.Index (Extension)
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
      Executing action method Extension.Controllers.DefaultController.Index (Extension) - Validation state: Valid
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
      Executed action method Extension.Controllers.DefaultController.Index (Extension), returned result Microsoft.AspNetCore.Mvc.ViewResult in 0.3428ms.
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
      Executed action Extension.Controllers.DefaultController.Index (Extension) in 72.6227ms
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HLJI34PLKR1K", Request id "0HLJI34PLKR1K:00000001": An unhandled exception was thrown by the application.
System.InvalidOperationException: Cannot find compilation library location for package 'Microsoft.NETCore.App'
   at Microsoft.Extensions.DependencyModel.CompilationLibrary.ResolveReferencePaths(ICompilationAssemblyResolver resolver, List`1 assemblies)
   at Microsoft.Extensions.DependencyModel.CompilationLibrary.ResolveReferencePaths()
   at Microsoft.AspNetCore.Mvc.ApplicationParts.AssemblyPart.<>c.<GetReferencePaths>b__8_0(CompilationLibrary library)
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at Microsoft.AspNetCore.Mvc.Razor.Compilation.MetadataReferenceFeatureProvider.PopulateFeature(IEnumerable`1 parts, MetadataReferenceFeature feature)
   at Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPartManager.PopulateFeature[TFeature](TFeature feature)
   at Microsoft.AspNetCore.Mvc.Razor.Internal.DefaultRazorReferenceManager.GetCompilationReferences()
   at System.Threading.LazyInitializer.EnsureInitializedCore[T](T& target, Boolean& initialized, Object& syncLock, Func`1 valueFactory)
   at Microsoft.AspNetCore.Mvc.Razor.Internal.DefaultRazorReferenceManager.get_CompilationReferences()
   at Microsoft.AspNetCore.Mvc.Razor.Internal.LazyMetadataReferenceFeature.get_References()
   at Microsoft.CodeAnalysis.Razor.CompilationTagHelperFeature.GetDescriptors()
   at Microsoft.AspNetCore.Razor.Language.DefaultRazorTagHelperBinderPhase.ExecuteCore(RazorCodeDocument codeDocument)
   at Microsoft.AspNetCore.Razor.Language.RazorEnginePhaseBase.Execute(RazorCodeDocument codeDocument)
   at Microsoft.AspNetCore.Razor.Language.DefaultRazorEngine.Process(RazorCodeDocument document)
   at Microsoft.AspNetCore.Razor.Language.DefaultRazorProjectEngine.ProcessCore(RazorCodeDocument codeDocument)
   at Microsoft.AspNetCore.Razor.Language.RazorProjectEngine.Process(RazorProjectItem projectItem)
   at Microsoft.AspNetCore.Mvc.Razor.Internal.RazorViewCompiler.CompileAndEmit(String relativePath)
   at Microsoft.AspNetCore.Mvc.Razor.Internal.RazorViewCompiler.OnCacheMiss(String normalizedPath)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Razor.Internal.DefaultRazorPageFactoryProvider.CreateFactory(String relativePath)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.CreateCacheResult(HashSet`1 expirationTokens, String relativePath, Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.OnCacheMiss(ViewLocationExpanderContext expanderContext, ViewLocationCacheKey cacheKey)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.LocatePageFromViewLocations(ActionContext actionContext, String pageName, Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.FindView(ActionContext context, String viewName, Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.ViewEngines.CompositeViewEngine.FindView(ActionContext context, String viewName, Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.FindView(ActionContext actionContext, ViewResult viewResult)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.ExecuteAsync(ActionContext context, ViewResult result)
   at Microsoft.AspNetCore.Mvc.ViewResult.ExecuteResultAsync(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultAsync(IActionResult result)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResultFilterAsync[TFilter,TFilterAsync]()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResultExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultFilters()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 173.6691ms 500
	  
```

Am I doing something wrong - what's the problem?

**Comment by DmitrySikorsky** [comment]
Thanks, I will check that and come back to you.

**Comment by DmitrySikorsky** [comment]
So, I have tested this and it works as you described. If I return anything else except a view from the controller it works perfectly. It also works if I remove dependency on the Microsoft.AspNetCore.App metapackage from the main web app. I think it is related to: https://github.com/dotnet/sdk/issues/2442.

**Comment by Xarkam** [comment]
Hello, we don't have same error :
```
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
      Executed action Extension.Controllers.DefaultController.Index (Extension) in 2552.6418ms
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HLJKS01C6U56", Request id "0HLJKS01C6U56:00000001": An unhandled exception was thrown by the application.
Microsoft.AspNetCore.Mvc.Razor.Compilation.CompilationFailedException: One or more compilation failures occurred:
i3ajozlx.b4z(4,55): error CS0012: The type 'Attribute' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
i3ajozlx.b4z(5,62): error CS0012: The type 'Attribute' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
i3ajozlx.b4z(4,82): error CS0518: Predefined type 'System.Type' is not defined or imported
i3ajozlx.b4z(4,123): error CS0518: Predefined type 'System.String' is not defined or imported
i3ajozlx.b4z(4,140): error CS0518: Predefined type 'System.String' is not defined or imported
i3ajozlx.b4z(4,12): error CS0518: Predefined type 'System.Void' is not defined or imported
i3ajozlx.b4z(5,81): error CS0518: Predefined type 'System.String' is not defined or imported
i3ajozlx.b4z(5,113): error CS0518: Predefined type 'System.Type' is not defined or imported
i3ajozlx.b4z(5,11): error CS0518: Predefined type 'System.Void' is not defined or imported
i3ajozlx.b4z(16,49): error CS0012: The type 'Attribute' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
i3ajozlx.b4z(17,49): error CS0012: The type 'Attribute' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
i3ajozlx.b4z(16,78): error CS0518: Predefined type 'System.String' is not defined or imported
i3ajozlx.b4z(16,87): error CS0518: Predefined type 'System.String' is not defined or imported
i3ajozlx.b4z(16,132): error CS0518: Predefined type 'System.String' is not defined or imported
i3ajozlx.b4z(16,6): error CS0518: Predefined type 'System.Void' is not defined or imported
i3ajozlx.b4z(17,78): error CS0518: Predefined type 'System.String' is not defined or imported
i3ajozlx.b4z(17,87): error CS0518: Predefined type 'System.String' is not defined or imported
i3ajozlx.b4z(17,132): error CS0518: Predefined type 'System.String' is not defined or imported
i3ajozlx.b4z(17,6): error CS0518: Predefined type 'System.Void' is not defined or imported
i3ajozlx.b4z(18,90): error CS0518: Predefined type 'System.Boolean' is not defined or imported
i3ajozlx.b4z(18,41): error CS0012: The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
i3ajozlx.b4z(21,67): error CS1983: The return type of an async method must be void, Task or Task<T>
i3ajozlx.b4z(21,62): error CS1069: The type name 'Task' could not be found in the namespace 'System.Threading.Tasks'. This type has been forwarded to assembly 'System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e' Consider adding a reference to that assembly.
i3ajozlx.b4z(32,118): error CS0518: Predefined type 'System.Void' is not defined or imported
i3ajozlx.b4z(34,71): error CS0518: Predefined type 'System.Void' is not defined or imported
i3ajozlx.b4z(36,87): error CS0518: Predefined type 'System.Void' is not defined or imported
i3ajozlx.b4z(38,83): error CS0518: Predefined type 'System.Void' is not defined or imported
i3ajozlx.b4z(40,71): error CS0012: The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
i3ajozlx.b4z(40,71): error CS0518: Predefined type 'System.Object' is not defined or imported
i3ajozlx.b4z(40,71): error CS0518: Predefined type 'System.Boolean' is not defined or imported
i3ajozlx.b4z(40,92): error CS0518: Predefined type 'System.Void' is not defined or imported
i3ajozlx.b4z(21,67): error CS0508: '_Views_Default_Index.ExecuteAsync()': return type must be 'Task' to match overridden member 'RazorPageBase.ExecuteAsync()'
i3ajozlx.b4z(21,67): error CS0012: The type 'Task' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
i3ajozlx.b4z(31,58): error CS0012: The type 'Attribute' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
i3ajozlx.b4z(31,10): error CS0518: Predefined type 'System.Void' is not defined or imported
i3ajozlx.b4z(33,58): error CS0012: The type 'Attribute' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
i3ajozlx.b4z(33,10): error CS0518: Predefined type 'System.Void' is not defined or imported
i3ajozlx.b4z(35,58): error CS0012: The type 'Attribute' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
i3ajozlx.b4z(35,10): error CS0518: Predefined type 'System.Void' is not defined or imported
i3ajozlx.b4z(37,58): error CS0012: The type 'Attribute' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
i3ajozlx.b4z(37,10): error CS0518: Predefined type 'System.Void' is not defined or imported
i3ajozlx.b4z(39,58): error CS0012: The type 'Attribute' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
i3ajozlx.b4z(39,10): error CS0518: Predefined type 'System.Void' is not defined or imported
i3ajozlx.b4z(23,13): error CS0012: The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
i3ajozlx.b4z(23,13): error CS0518: Predefined type 'System.Object' is not defined or imported
i3ajozlx.b4z(23,26): error CS0518: Predefined type 'System.Int32' is not defined or imported
i3ajozlx.b4z(23,30): error CS0518: Predefined type 'System.Int32' is not defined or imported
i3ajozlx.b4z(23,33): error CS0518: Predefined type 'System.Boolean' is not defined or imported
i3ajozlx.b4z(23,13): error CS0518: Predefined type 'System.Void' is not defined or imported
i3ajozlx.b4z(24,13): error CS0012: The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
i3ajozlx.b4z(24,13): error CS0518: Predefined type 'System.Object' is not defined or imported
i3ajozlx.b4z(24,26): error CS0518: Predefined type 'System.String' is not defined or imported
i3ajozlx.b4z(24,13): error CS0518: Predefined type 'System.Void' is not defined or imported
i3ajozlx.b4z(25,13): error CS0012: The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
i3ajozlx.b4z(25,13): error CS0518: Predefined type 'System.Object' is not defined or imported
i3ajozlx.b4z(25,13): error CS0518: Predefined type 'System.Void' is not defined or imported
i3ajozlx.b4z(26,13): error CS0012: The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
i3ajozlx.b4z(26,13): error CS0518: Predefined type 'System.Object' is not defined or imported
i3ajozlx.b4z(26,26): error CS0518: Predefined type 'System.Int32' is not defined or imported
i3ajozlx.b4z(26,31): error CS0518: Predefined type 'System.Int32' is not defined or imported
i3ajozlx.b4z(26,35): error CS0518: Predefined type 'System.Boolean' is not defined or imported
i3ajozlx.b4z(26,13): error CS0518: Predefined type 'System.Void' is not defined or imported
i3ajozlx.b4z(27,13): error CS0012: The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
i3ajozlx.b4z(27,13): error CS0518: Predefined type 'System.Object' is not defined or imported
i3ajozlx.b4z(27,26): error CS0518: Predefined type 'System.String' is not defined or imported
i3ajozlx.b4z(27,13): error CS0518: Predefined type 'System.Void' is not defined or imported
i3ajozlx.b4z(28,13): error CS0012: The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
i3ajozlx.b4z(28,13): error CS0518: Predefined type 'System.Object' is not defined or imported
i3ajozlx.b4z(28,13): error CS0518: Predefined type 'System.Void' is not defined or imported
i3ajozlx.b4z(21,67): error CS0161: '_Views_Default_Index.ExecuteAsync()': not all code paths return a value
i3ajozlx.b4z(18,18): error CS0518: Predefined type 'System.Void' is not defined or imported
   at Microsoft.AspNetCore.Mvc.Razor.Internal.RazorViewCompiler.CompileAndEmit(RazorCodeDocument codeDocument, String generatedCode)
   at Microsoft.AspNetCore.Mvc.Razor.Internal.RazorViewCompiler.CompileAndEmit(String relativePath)
   at Microsoft.AspNetCore.Mvc.Razor.Internal.RazorViewCompiler.OnCacheMiss(String normalizedPath)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Razor.Internal.DefaultRazorPageFactoryProvider.CreateFactory(String relativePath)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.CreateCacheResult(HashSet`1 expirationTokens, String relativePath, Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.OnCacheMiss(ViewLocationExpanderContext expanderContext, ViewLocationCacheKey cacheKey)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.LocatePageFromViewLocations(ActionContext actionContext, String pageName, Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.FindView(ActionContext context, String viewName, Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.ViewEngines.CompositeViewEngine.FindView(ActionContext context, String viewName, Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.FindView(ActionContext actionContext, ViewResult viewResult)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.ExecuteAsync(ActionContext context, ViewResult result)
   at Microsoft.AspNetCore.Mvc.ViewResult.ExecuteResultAsync(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultAsync(IActionResult result)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResultFilterAsync[TFilter,TFilterAsync]()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResultExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultFilters()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 2900.5911ms 500
Application is shutting down...
```
We continue our investigations

**Comment by Xarkam** [comment]
You must add
```
<PreserveCompilationContext>true</PreserveCompilationContext>
<MvcRazorExcludeRefAssembliesFromPublish>false</MvcRazorExcludeRefAssembliesFromPublish>
```
in your csproj files.

@Glusk2 reinstall netcore sdk, because, it's certainly broken.

**Comment by Xarkam** [comment]
We've found all these points of interests:
- you must modify all .csproj as stated in previous message :
```
<PreserveCompilationContext>true</PreserveCompilationContext>
<MvcRazorExcludeRefAssembliesFromPublish>false</MvcRazorExcludeRefAssembliesFromPublish>
```
- when Extension.dll is located in /Extensions folder, the webapp cannot find it at runtime.
- when Extension.dll is located near WebApplication.dll, it's found.

**It's required to copy the files in "refs" folder (generated by publishing a project) to the "refs" folder of startup project.**

In your case, Extension.dll requires `System.ComponentModel.Composition.dll` so it should be copied from Extension project publication refs folder to WebApplication project publication refs folder, and it works...
![image](https://user-images.githubusercontent.com/331816/50794902-cf2d6d80-12cc-11e9-8739-18aede672bd9.png)

```
 ⨯ Xarkam@HYKSOS  C:\Developpement\ExtCore-Sample-Mvc\src\WebApplication\bin\Release\netcoreapp2.2\publish   master ≣ ~2 -0 !  dotnet .\WebApplication.dll
info: ExtCore.WebApplication[0]
      Discovering and loading assemblies from DependencyContext
info: ExtCore.WebApplication[0]
      Assembly 'WebApplication, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' is discovered and loaded
info: ExtCore.WebApplication[0]
      Assembly 'ExtCore.Infrastructure, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null' is discovered and loaded
info: ExtCore.WebApplication[0]
      Assembly 'ExtCore.Mvc, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null' is discovered and loaded
info: ExtCore.WebApplication[0]
      Assembly 'ExtCore.Mvc.Infrastructure, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null' is discovered and loaded
info: ExtCore.WebApplication[0]
      Assembly 'ExtCore.WebApplication, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null' is discovered and loaded
info: ExtCore.WebApplication[0]
      Discovering and loading assemblies from path 'C:\Developpement\ExtCore-Sample-Mvc\src\WebApplication\bin\Release\netcoreapp2.2\publish/Extensions'
info: ExtCore.WebApplication[0]
      Assembly 'Extension, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' is discovered and loaded
info: ExtCore.WebApplication[0]
      Executing ConfigureServices action 'ExtCore.Mvc.Actions.AddStaticFilesAction'
info: ExtCore.WebApplication[0]
      Executing ConfigureServices action 'ExtCore.Mvc.Actions.AddMvcAction'
info: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[0]
      User profile is available. Using 'C:\Users\Xarkam\AppData\Local\ASP.NET\DataProtection-Keys' as key repository and Windows DPAPI to encrypt keys at rest.
info: ExtCore.WebApplication[0]
      Executing Configure action 'ExtCore.Mvc.Actions.UseStaticFilesAction'
info: ExtCore.WebApplication[0]
      Executing Configure action 'ExtCore.Mvc.Actions.UseMvcAction'
info: ExtCore.Mvc[0]
      Executing UseMvc action 'Extension.Actions.UseMvcAction'
Hosting environment: Production
Content root path: C:\Developpement\ExtCore-Sample-Mvc\src\WebApplication\bin\Release\netcoreapp2.2\publish
Now listening on: http://localhost:5000
Now listening on: https://localhost:5001
Application started. Press Ctrl+C to shut down.
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:5000/
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
      Route matched with {action = "Index", controller = "Default"}. Executing action Extension.Controllers.DefaultController.Index (Extension)
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
      Executing action method Extension.Controllers.DefaultController.Index (Extension) - Validation state: Valid
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
      Executed action method Extension.Controllers.DefaultController.Index (Extension), returned result Microsoft.AspNetCore.Mvc.ViewResult in 0.2404ms.
info: Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor[1]
      Executing ViewResult, running view Index.
info: Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor[4]
      Executed ViewResult - view Index executed in 1605.3593ms.
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
      Executed action Extension.Controllers.DefaultController.Index (Extension) in 1620.457ms
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 1709.8578ms 200 text/html; charset=utf-8
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:5000/Styles.default.css
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[6]
      The file /Styles.default.css was not modified
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 9.8276ms 304 text/css
```

In my tests with `-r win10-x64` flag, others problems appear
